import './globals.scss'
import { Inter } from 'next/font/google'
import Header from './Components/Header'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Spotify Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-base text-white  `} >
     
        <div className="grid grid-cols-[1fr_auto] grid-rows-[auto_1fr] min-h-screen p-4 ">
        <Header/>
          {children}
          </div>
      </body>
    </html>
  )
}

